
"use client";

import { useState, useEffect, useRef } from 'react';
import { useRouter } from 'next/navigation'; 
import { PageHeader } from '@/components/custom/PageHeader';
import { Button } from '@/components/ui/button';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { useToast } from '@/hooks/use-toast';
import { Camera, QrCode, AlertTriangle } from 'lucide-react';

export default function ScanTableQrPage() {
  const { toast } = useToast();
  const router = useRouter(); 
  const videoRef = useRef<HTMLVideoElement>(null);
  const [hasCameraPermission, setHasCameraPermission] = useState<boolean | null>(null);
  const [scannedData, setScannedData] = useState<string | null>(null);
  const [isScanning, setIsScanning] = useState<boolean>(false);

  useEffect(() => {
    const getCameraPermission = async () => {
      if (!navigator.mediaDevices || !navigator.mediaDevices.getUserMedia) {
        console.error('Camera API not supported.');
        setHasCameraPermission(false);
        toast({
          variant: 'destructive',
          title: 'الكاميرا غير مدعومة',
          description: 'متصفحك لا يدعم الوصول إلى الكاميرا.',
        });
        return;
      }
      try {
        const stream = await navigator.mediaDevices.getUserMedia({ video: { facingMode: "environment" } });
        setHasCameraPermission(true);
        if (videoRef.current) {
          videoRef.current.srcObject = stream;
        }
      } catch (error) {
        console.error('Error accessing camera:', error);
        setHasCameraPermission(false);
        toast({
          variant: 'destructive',
          title: 'تم رفض الوصول إلى الكاميرا',
          description: 'يرجى تمكين صلاحيات الكاميرا في متصفحك لاستخدام هذه الميزة.',
        });
      }
    };

    if (isScanning) {
        getCameraPermission();
    } else {
        if (videoRef.current && videoRef.current.srcObject) {
            const stream = videoRef.current.srcObject as MediaStream;
            stream.getTracks().forEach(track => track.stop());
            videoRef.current.srcObject = null;
        }
    }
    
    return () => {
        if (videoRef.current && videoRef.current.srcObject) {
            const stream = videoRef.current.srcObject as MediaStream;
            stream.getTracks().forEach(track => track.stop());
        }
    };
  }, [isScanning, toast]);

  const handleScanSuccess = (data: string | null) => {
    if (data) {
      setScannedData(data); // Keep the raw scanned data for display if needed
      setIsScanning(false);
      
      try {
        // Assuming data is a relative URL like "/website/menu?table_id=t1&table_number=1"
        // Or an absolute URL if scanned by an external app that resolved it.
        // We need to handle both cases if the in-app scanner might scan either.
        // For simplicity, let's assume the in-app scanner always gets the relative path.
        const url = new URL(data, window.location.origin); // Use current origin as base if data is relative
        const tableId = url.searchParams.get('table_id');
        const tableNumber = url.searchParams.get('table_number');

        if (tableId && tableNumber) {
          localStorage.setItem('customer_selected_table_id', tableId);
          localStorage.setItem('customer_selected_table_number', tableNumber);
          toast({
            title: 'تم تحديد الطاولة بنجاح!',
            description: `طاولة رقم ${tableNumber}. سيتم توجيهك إلى القائمة للطلب.`,
          });
          router.push('/website/menu'); // Redirect to the base menu page
        } else {
          toast({
            variant: 'destructive',
            title: 'خطأ في بيانات الـ QR',
            description: 'لم يتم التعرف على بيانات الطاولة من الرمز الممسوح. تأكد أن الرمز يحتوي على table_id و table_number.',
          });
        }
      } catch (e) {
        console.error("Error parsing QR data URL:", e);
        toast({
          variant: 'destructive',
          title: 'خطأ في بيانات الـ QR',
          description: 'تنسيق البيانات في الرمز الممسوح غير صحيح.',
        });
      }
    }
  };

  const handleScanError = (error: any) => {
    console.error('QR Scan Error:', error);
    toast({
      variant: 'destructive',
      title: 'خطأ في مسح الـ QR',
      description: 'لم نتمكن من قراءة الرمز. يرجى المحاولة مرة أخرى.',
    });
  };
  
  // Example QR data that would be generated by TableCard.tsx
  // This should match the format generated by TableCard: /website/menu?table_id=TABLE_ID_HERE&table_number=TABLE_NUMBER_HERE
  const exampleQrDataForTable1 = `/website/menu?table_id=t1&table_number=1`;


  if (hasCameraPermission === false && isScanning) {
    return (
      <div className="container mx-auto py-8">
        <PageHeader title="مسح QR الطاولة" description="قم بتوجيه الكاميرا نحو رمز QR الموجود على طاولتك." icon={QrCode} />
        <Alert variant="destructive" className="my-4">
          <AlertTriangle className="h-4 w-4" />
          <AlertTitle>الوصول إلى الكاميرا مطلوب</AlertTitle>
          <AlertDescription>
            يرجى تمكين صلاحيات الكاميرا في إعدادات المتصفح الخاص بك لمسح رمز QR.
          </AlertDescription>
        </Alert>
         <Button onClick={() => setIsScanning(false)} variant="outline">إلغاء المسح</Button>
      </div>
    );
  }

  return (
    <div className="container mx-auto py-8">
      <PageHeader title="مسح QR الطاولة" description="قم بتوجيه الكاميرا نحو رمز QR الموجود على طاولتك لبدء الطلب." icon={QrCode} />
      
      <div className="flex flex-col items-center gap-6 mt-8">
        {!isScanning && !scannedData && (
             <Button onClick={() => setIsScanning(true)} size="lg" className="bg-primary hover:bg-primary/90 text-primary-foreground">
                <Camera className="me-2 h-5 w-5" />
                ابدأ مسح QR الطاولة
            </Button>
        )}

        {isScanning && (
          <div className="w-full max-w-md p-4 border-2 border-dashed border-primary rounded-lg bg-card shadow-lg">
            <video ref={videoRef} className="w-full aspect-video rounded-md" autoPlay muted playsInline />
            <p className="text-center text-muted-foreground mt-2">جاري البحث عن رمز QR...</p>
            <Button onClick={() => handleScanSuccess(exampleQrDataForTable1)} className="w-full mt-4">
              محاكاة مسح ناجح (طاولة 1)
            </Button>
            <Button onClick={() => setIsScanning(false)} variant="outline" className="w-full mt-2">إلغاء المسح</Button>
          </div>
        )}

        {scannedData && !isScanning && ( 
          <Alert className="max-w-md">
            <QrCode className="h-4 w-4" />
            <AlertTitle>تم المسح بنجاح!</AlertTitle>
            <AlertDescription>
              بيانات الـQR الممسوحة: <strong>{scannedData}</strong>
              <br />
              جاري توجيهك إلى قائمة الطعام...
            </AlertDescription>
             <Button onClick={() => { setScannedData(null); setIsScanning(true);}} className="mt-4">مسح رمز آخر</Button>
          </Alert>
        )}
      </div>
    </div>
  );
}

